name: tool-use-journal

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - pip:
      - robosuite==1.5.2
      - mujoco==3.3.1
      - numpy==2.2.5
      - numba==0.61.2
      - scipy==1.15.3
      - PyYAML>=6.0
      - Pillow
      - opencv-python
      - imageio
      - h5py
      - lxml
      - pynput
      - tqdm
      - termcolor
      - pygame
      - gymnasium
      - hidapi
