"""Fixed failure and recovery vocabularies for M6."""

FAILURE_VOCABULARY = {
    "TASK_DECOMPOSITION": ("MISSING_SUBGOAL", "WRONG_SUBGOAL_ORDER", "INVALID_CONDITION", "WRONG_ACTION_TYPE"),
    "PERCEPTION_GROUNDING": ("OBJECT_NOT_DETECTED", "WRONG_OBJECT_IDENTITY", "WRONG_OBJECT_STATE", "OCCLUSION", "STALE_SCENE"),
    "METRIC_REASONING": ("WRONG_MASS_ESTIMATE", "WRONG_FRICTION_ESTIMATE", "WRONG_DIMENSION_ESTIMATE", "WRONG_DISTANCE", "WRONG_CLEARANCE", "WRONG_FIT_ESTIMATE"),
    "EE_SELECTION": ("INCOMPATIBLE_EE", "INSUFFICIENT_GRASP_STABILITY", "INSUFFICIENT_PAYLOAD", "INSUFFICIENT_APERTURE", "SUCTION_INFEASIBLE"),
    "PLANNING": ("IK_FAILURE", "COLLISION", "UNREACHABLE_POSE", "INVALID_APPROACH", "TRAJECTORY_FAILURE"),
    "EXECUTION_CONTROL": ("GRASP_FAILURE", "SLIP", "RELEASE_FAILURE", "CONTROL_ERROR", "TIMEOUT"),
    "ENVIRONMENT_CHANGE": ("OBJECT_MOVED", "OBSTACLE_CHANGED", "TARGET_STATE_CHANGED", "SCENE_CHANGED"),
}

FAILURE_MODULES = {
    "TASK_DECOMPOSITION": "M2",
    "PERCEPTION_GROUNDING": "M1",
    "METRIC_REASONING": "M3",
    "EE_SELECTION": "M4",
    "PLANNING": "M5",
    "EXECUTION_CONTROL": "Controller",
    "ENVIRONMENT_CHANGE": "M1",
}

RECOVERY_VOCABULARY = {
    "REPLAN_SUBGOAL": ("REDECOMPOSE_SUBGOAL", "REORDER_SUBGOALS", "UPDATE_CONDITION"),
    "REOBSERVE": ("REOBSERVE_OBJECT", "REOBSERVE_SCENE", "CHANGE_VIEWPOINT"),
    "REMEASURE": ("REMEASURE_PROPERTY", "RECOMPUTE_RELATION"),
    "RESELECT_EE": ("RESELECT_EE", "EXCLUDE_EE"),
    "REPLAN_MOTION": ("REPLAN_MOTION", "CHANGE_APPROACH", "ADD_WAYPOINT"),
    "RETRY_EXECUTION": ("RETRY_ACTION", "ADJUST_FORCE", "ADJUST_SPEED", "APPLY_OFFSET"),
    "UPDATE_SCENE": ("UPDATE_OBJECT_STATE", "UPDATE_RELATION", "INVALIDATE_SCENE_INFO"),
    "ESCALATE_REPLAN": ("ESCALATE_TO_SUBGOAL", "RESTART_PIPELINE"),
}

RECOVERY_CATEGORY_MODULES = {
    "REPLAN_SUBGOAL": "M2",
    "REOBSERVE": "M1",
    "REMEASURE": "M3",
    "RESELECT_EE": "M4",
    "REPLAN_MOTION": "M5",
    "RETRY_EXECUTION": "Controller",
    "UPDATE_SCENE": "M1",
    "ESCALATE_REPLAN": "M2",
}

RECOVERY_ACTION_MODULES = {
    "REDECOMPOSE_SUBGOAL": "M2",
    "REORDER_SUBGOALS": "M2",
    "UPDATE_CONDITION": "M2",
    "REOBSERVE_OBJECT": "M1",
    "REOBSERVE_SCENE": "M1",
    "CHANGE_VIEWPOINT": "M1",
    "REMEASURE_PROPERTY": "M3",
    "RECOMPUTE_RELATION": "M3",
    "RESELECT_EE": "M4",
    "EXCLUDE_EE": "M4",
    "REPLAN_MOTION": "M5",
    "CHANGE_APPROACH": "M5",
    "ADD_WAYPOINT": "M5",
    "RETRY_ACTION": "Controller",
    "ADJUST_FORCE": "Controller",
    "ADJUST_SPEED": "Controller",
    "APPLY_OFFSET": "Controller",
    "UPDATE_OBJECT_STATE": "M1",
    "UPDATE_RELATION": "M1",
    "INVALIDATE_SCENE_INFO": "M1",
    "ESCALATE_TO_SUBGOAL": "M2",
    "RESTART_PIPELINE": "M2",
}

FAILURE_TYPE_TO_RECOVERY_CATEGORY = {
    "TASK_DECOMPOSITION": "REPLAN_SUBGOAL",
    "PERCEPTION_GROUNDING": "REOBSERVE",
    "METRIC_REASONING": "REMEASURE",
    "EE_SELECTION": "RESELECT_EE",
    "PLANNING": "REPLAN_MOTION",
    "EXECUTION_CONTROL": "RETRY_EXECUTION",
    "ENVIRONMENT_CHANGE": "UPDATE_SCENE",
}

RECOVERY_CATEGORY_DEFAULT_ACTION = {
    category: actions[0]
    for category, actions in RECOVERY_VOCABULARY.items()
}

FAILURE_CAUSE_TO_RECOVERY_ACTION = {
    "MISSING_SUBGOAL": "REDECOMPOSE_SUBGOAL",
    "WRONG_SUBGOAL_ORDER": "REORDER_SUBGOALS",
    "INVALID_CONDITION": "UPDATE_CONDITION",
    "WRONG_ACTION_TYPE": "REDECOMPOSE_SUBGOAL",
    "OBJECT_NOT_DETECTED": "REOBSERVE_OBJECT",
    "WRONG_OBJECT_IDENTITY": "REOBSERVE_OBJECT",
    "WRONG_OBJECT_STATE": "REOBSERVE_SCENE",
    "OCCLUSION": "CHANGE_VIEWPOINT",
    "STALE_SCENE": "INVALIDATE_SCENE_INFO",
    "WRONG_MASS_ESTIMATE": "REMEASURE_PROPERTY",
    "WRONG_FRICTION_ESTIMATE": "REMEASURE_PROPERTY",
    "WRONG_DIMENSION_ESTIMATE": "REMEASURE_PROPERTY",
    "WRONG_DISTANCE": "RECOMPUTE_RELATION",
    "WRONG_CLEARANCE": "RECOMPUTE_RELATION",
    "WRONG_FIT_ESTIMATE": "RECOMPUTE_RELATION",
    "INCOMPATIBLE_EE": "RESELECT_EE",
    "INSUFFICIENT_GRASP_STABILITY": "RESELECT_EE",
    "INSUFFICIENT_PAYLOAD": "RESELECT_EE",
    "INSUFFICIENT_APERTURE": "RESELECT_EE",
    "SUCTION_INFEASIBLE": "RESELECT_EE",
    "IK_FAILURE": "REPLAN_MOTION",
    "COLLISION": "REPLAN_MOTION",
    "UNREACHABLE_POSE": "REPLAN_MOTION",
    "INVALID_APPROACH": "CHANGE_APPROACH",
    "TRAJECTORY_FAILURE": "REPLAN_MOTION",
    "GRASP_FAILURE": "RETRY_ACTION",
    "SLIP": "RETRY_ACTION",
    "RELEASE_FAILURE": "RETRY_ACTION",
    "CONTROL_ERROR": "RETRY_ACTION",
    "TIMEOUT": "RETRY_ACTION",
    "OBJECT_MOVED": "UPDATE_OBJECT_STATE",
    "OBSTACLE_CHANGED": "UPDATE_RELATION",
    "TARGET_STATE_CHANGED": "UPDATE_OBJECT_STATE",
    "SCENE_CHANGED": "INVALIDATE_SCENE_INFO",
}

RECOVERY_ROUTING_PROFILES = {
    "INVALIDATE_SCENE_INFO": {
        "restart_from": "M1",
        "rerun_modules": ["M1"],
        "invalidate": ["M0"],
    },
    "ESCALATE_TO_SUBGOAL": {
        "restart_from": "M2",
        "rerun_modules": ["M2"],
        "invalidate": [],
    },
    "RESTART_PIPELINE": {
        "restart_from": "M1",
        "rerun_modules": ["M1", "M2"],
        "invalidate": [],
    },
}

VALID_ROUTING_MODULES = frozenset(
    {"M0", "M1", "M2", "M3", "M4", "M5", "Controller", "M6"}
)
